### ISSUE TITLE
[Request]: Meta Package Manager

### ISSUE THREAD

**Issue by wickles** [ScoopInstaller/Main#5448]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

meta-package-manager

### Description

wraps all package managers with a unifying CLI

### Homepage

https://kdeldycke.github.io/meta-package-manager/
https://github.com/kdeldycke/meta-package-manager

### Download Link(s)

https://github.com/kdeldycke/meta-package-manager/releases/download/v5.14.2/mpm-windows-x64.exe

### Some Indication of Popularity/Repute

420 ⭐

**Comment by wickles** [comment]
Is 500 stars a strict requirement?

**Comment by rashil2000** [comment]
> Is 500 stars a strict requirement?

No.

Please make a PR for your request!
